import { GridLocaleText } from "@mui/x-data-grid";

export const localeText: Partial<GridLocaleText> = {
  toolbarExport: "Pobierz",
  toolbarExportPrint: "Wydrukuj",
  toolbarExportCSV: "Pobierz plik CSV",
  toolbarDensity: "Gęstość",
  toolbarDensityStandard: "Standard",
  toolbarDensityComfortable: "Komfort",
  toolbarDensityCompact: "Kompakt",
  toolbarFilters: "Filtry",
  toolbarFiltersLabel: "Filtry",
  toolbarColumns: "Kolumny",
  toolbarColumnsLabel: "Kolumny",
  filterPanelColumns: "Kolumna",
  filterPanelOperator: "Operator",
  filterPanelAddFilter: "Dodaj filtr",
  filterPanelInputLabel: "Wartość",
  filterPanelInputPlaceholder: "Filtruj wartość",
  footerTotalRows: "Suma wierszów",
  noRowsLabel: "Brak danych",
  booleanCellFalseLabel: "Nie",
  booleanCellTrueLabel: "Tak",
  "filterOperator!=": "różne od",
  filterOperatorAfter: "po",
  filterOperatorBefore: "przed",
  filterOperatorContains: "zawiera",
  filterOperatorEndsWith: "kończy się na",
  filterOperatorEquals: "równe",
  filterOperatorIs: "jest",
  filterOperatorIsAnyOf: "jest jednym z",
  filterOperatorIsEmpty: "jest pusty",
  filterOperatorIsNotEmpty: "nie jest pusty",
  filterOperatorNot: "nie",
  filterOperatorOnOrAfter: "w dniu lub po",
  filterOperatorOnOrBefore: "w dniu lub przed",
  "filterOperator<": "mniejsze niż",
  "filterOperator<=": "mniejsze lub równe",
  "filterOperator=": "równe",
  filterOperatorStartsWith: "zaczyna się na",
  "filterOperator>": "większe niż",
  "filterOperator>=": "większe lub równe",
  filterPanelOperatorAnd: "oraz",
  filterPanelOperatorOr: "lub",
  footerRowSelected: (count) =>
    count !== 1
      ? `${count.toLocaleString()} wiersze zaznaczone`
      : `${count.toLocaleString()} wiersz zaznaczony`,
  MuiTablePagination: {
    labelRowsPerPage: "Wiersze na stronę:",
    labelDisplayedRows: ({ from, to, count }) =>
      `${from}–${to} z ${count !== -1 ? count : `ponad ${to}`}`,
  },
};
